logging:
  level: INFO
  loggers:
    com.jingyuyao.shortener: DEBUG

database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shortener_primary
  user: tester  # TODO(jingyu): Use environment variables
  password: test
  properties:
    characterEncoding: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    serverTimezone: UTC
    useSSL: false  # TODO(jingyu): Set up SSL in prod
    useUnicode: true

jedis:
  host: localhost